// Generated by CoffeeScript 1.12.7
(function() {
  var person;

  person = {
    name: 'Trey',
    distance_travelled: 0,
    say_name: function() {
      return alert(this.name);
    },
    say_something: function(param) {
      return console.log(this.name + " says '" + param + "'");
    },
    walk: function() {
      console.log(this.name + " is walking");
      return this.distance_travelled += 3;
    },
    run: function() {
      console.log(this.name + " is running");
      return this.distance_travelled += 10;
    },
    crawling: function() {
      console.log(this.name + " is crawling");
      return this.distance_travelled += 1;
    }
  };

  person.say_something('thank you');

  person.run();

  console.log(person.distance_travelled);

}).call(this);
